### ISSUE TITLE
menu scene + backspace interaction

### ISSUE THREAD

**Issue by patxu** [patxu/cs98-senior-project#211]
hold colors don't reset when going back to the menu scene. going from music -> menu, all the holds are teal

**Comment by jpkramer** [comment]
@patxu @db2882 @relchar @olykos 

This is related to several issues. There is a new flow for the holds. The Hold GameObjects that are passed from scene to scene should be essentially containing only position and scale. Add child game objects to the hold in order to add more functionality. This would include rendering the display of the hold (Line Renderer or Sprite Renderer) and putting specific hit boxes (colliders). This style is very standard Unity as it keeps functionality separated so it doesnt interfere. 

That said for now and for the demo we are going to start by using this method to abstract the sprite rendering to a child object. This is in fact a necessity in order to get the sprite to display properly without affecting the colliders. 

To work with the current set up, expect hold game objects to have a line renderer (to display the circles as we usually do) and the necessary colliders. Nothing here has changed!!!!
If we have time and certainly in the future we should work to move this functionality into child objects.

If you want to add a sprite you must explicitly to so by adding a child object. There will be no Sprite Renderer attached to a hold itself. You can use a prefab and we can write a helper method for this.

**IMPORTANT!!!**
This method means that at the end of a scene, all children of a hold object are destroyed, the line renderer is disabled, and all scene specific scripts attached to the hold are destroyed. The developer must ensure these tasks are handled as they do not happen by themselves. 

At the beginning of a new scene, it is up to the developer to enable the line renderer and set the color if they desire a circle drawn for a particular hold.

**SEE Menu.cs for an example of how things should be called**

The drawing of the circle should also eventually be made a separate explicit task, but for now the line renderer will be initialized with the circle and we will simply toggle its display and its color.
